name: "Telegram News Summary"
on:
  # Every 3 days at 09:00 UTC; adjust as needed
  schedule:
    - cron: '0 9 */3 * *'
  workflow_dispatch: {}

jobs:
  summary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Build and run summary script
        env:
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}        # Your Telegram API ID
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}    # Your Telegram API Hash
          TELEGRAM_STRING_SESSION: ${{ secrets.TELEGRAM_STRING_SESSION }}  # Generated session string
          TG_CHANNELS: ${{ secrets.TG_CHANNELS }}                # Comma-separated list of channel usernames
          TG_TARGET_CHAT_ID: ${{ secrets.TG_TARGET_CHAT_ID }}    # Chat ID to receive the summary
          DAYS: '3'                                              # Days back to fetch
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}          # For summarization
        run: |
          npm run build
          node dist/telegram-summary.js 